
#默认密码
#默认管理员账号密码、角色ID
user:
    onlineTimeout: 600000 #用户在线超时毫秒数
    defaultPwd: 111111
    admin:
        name: 超级管理员
        account: admin
        password: admin
        roleId: 0

spring:
  main:
    allow-bean-definition-overriding: true